version: '3'

services:
  sa-stac:
    container_name: stac-fastapi-sqlalchemy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8082
      - HOST=0.0.0.0
      - PORT=8082
      - ENVIRONMENT=local
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432
      - WEB_CONCURRENCY=10
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=10
      - MODULE_NAME=demo.sqlalchemy
      - VARIABLE_NAME=app
    ports:
      - "8082:8082"
    depends_on:
      - database

  pg-stac:
    container_name: stac-fastapi-pgstac
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8082
      - HOST=0.0.0.0
      - PORT=8082
      - ENVIRONMENT=local
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432
      - WEB_CONCURRENCY=10
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=10
      - MODULE_NAME=demo.pgstac
      - VARIABLE_NAME=app
    ports:
      - "8082:8082"
    depends_on:
      - database

  database:
    container_name: stac-db
    image: bitner/pgstac:0.2.7
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    ports:
      - "5439:5432"
    command: postgres -N 500

networks:
  default:
    name: stac-fastapi-network
